FROM golang:alpine

RUN apk update && apk add git

RUN mkdir -p /go/src/github.com/byuoitav
ADD . /go/src/github.com/byuoitav/kramer-microservice

WORKDIR /go/src/github.com/byuoitav/kramer-microservice
RUN go get -d -v
RUN go install -v

CMD ["/go/bin/kramer-microservice"]

EXPOSE 8014
